#!/bin/bash
##########################
## Script: 	spawn new ide session
## Author: 	kholinow
## Created: 	2015-11-28
##########################

SNAME=$1
if [ -z $SNAME ]; then
	SNAME="zIDE"
fi

tmux new-session -d -s "$SNAME" -n "IDE"
#tmux attach-session -t "$NAME"
#Window 1 IDE (vim + zsh x2)
tmux split-window -v -p 10
tmux split-window -h

#Window 2 local-etc (zsh x3, 1 big 2 small)
tmux new-window -t $SNAME:2 -n "local-etc"
tmux split-window -h -p 30
tmux split-window -v

#Window 3 remote-etc (zsh x3, 1 big 2 small)
tmux new-window -t $SNAME:3  -n "remote-etc"
tmux split-window -h -p 30
tmux split-window -v

#Window 4 elinks
tmux new-window -t $SNAME:4 -n "elinks"
tmux select-window -t $SNAME:4
tmux send-keys -t 0 "elinks" C-m 

tmux select-window -t $SNAME:1
tmux send-keys -t 0 "vim" C-m
tmux attach-session -t $SNAME
